### PR TITLE
[RESPONSIVENESS] - Improve styles for Desktop and Mobile.

### LINKED ISSUE #55: Mobile Responsiveness
I played on mobile with a friend to test if playing on a mobile device is good, so I have a suggestion for improving mobile responsiveness.

- [ ] Border-radius has a too thick thickness, making it difficult to read the block number.
- [ ] The game's width could be between 90% and 100%.
- [ ] Chat: Maybe could use v-lazy or v-textarea.
- [ ] Improve the visualization of v-card where there is a nickname, points, blick|bomb.

The image below shows how the screen looks on mobile devices.

Imagem1
Imagem2

### PR DESCRIPTION
**Pull request by neto112**
- [x] Border-radius has a too thick thickness, making it difficult to read the block number.
- [x] The game's width could be between 90% and 100%.
- [x] Chat: Maybe could use v-lazy or v-textarea.
- [x] Improve the visualization of v-card where there is a nickname, points, blick|bomb.

image
image
image
image

Closes #55

### CODE REVIEW

**Comment by Zomis** [comment]
Hi and a whole lot of thanks for your pull request!

When testing this I found a few things that seem a bit odd.

- Game map can get stretched out, the aspectRatio of the cells is not always 1.0 which makes them look weird. This is why I had some kind of code to measure available size and use the minimum of width/height, to make both width and height of the game map the same. (I honestly don't remember how I solved it in the existing code). If you have any possible solution for this, it would be great!
- In-game chat can cut off words right in the middle, no huge issue but I imagine it has a quite easy solution.
- Lobby chat doesn't seem to be functioning properly at all. I can't send messages and after a game is completed and I return to the lobby it doesn't show up at all. See attached screenshot that contains error log.

If there's anything I can do to help you with these issues, please let me know!

2024-02-07 20_33_48-Window
2024-02-07 20_34_45-Window
2024-02-07 20_37_02-Window

**Comment by neto112** [comment]
Hello, Simon.

Thank you for your feedback and for testing the PR... I aprreciate your attention to detail. I've addressed the issues you about:
- Game map aspect ratio;
- In-Game chat word cutting;
- Lobby Chat Issues (so, you shoud now be able to send messages in the lobby, and after completing a game, the chat must display as expected.

If there's anything specific you'd like me to address or if you have further questions, please don't hesitate to reach out.

**Comment by Zomis** [comment]
Nicely done! 👍 

If you want to help out further, I got some other projects that could use someone like you. :)

**Comment by neto112** [comment]
I'm glad to hear that the visual improvements in the project were appreciated. I'd be happy to help. Could you provide details about the next project or let me know how I can assist further?

**Comment by Zomis** [comment]
@neto112 Please join my Discord server https://discord.gg/GfXFUvc and ping me there (Zomis) 😃

**Pull request merged**
